---
roles:
  - name: clickhouse
    src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    version: "1.13"

  - name: initial
    src: https://github.com/expo-lux/ansible_initial.git
    version: "0.1.3"

  - name: zookeeper 
    src: https://github.com/idealista/zookeeper_role
    version: "2.2.0"

  - name: java
    src: https://github.com/geerlingguy/ansible-role-java.git
    version: "2.2.0"

collections:
  - name: community.general
    version: "5.7.0"
  
  - name: ansible.posix
    version: "1.4.0"

  - name: community.crypto
    version: "2.5.0"
...
